### PR TITLE
add /faq to nav bar, answer additional questions

### PR DESCRIPTION
**Pull request by hen6003**
I don't know how to test if this works and doesn't break

### CODE REVIEW

**Comment by con-f-use** [comment]
@paperbenni do not merge yet, we are collecting a few more questions. But **DO** comment and discuss!

**Comment by Pebor** [comment]
I mean "What about X feature? Is X planned? I've found a bug" something like that with a link to the roadmap + link to discord for suggestions and bug-reports?

**Comment by con-f-use** [comment]
> What about X feature? Is X planned?
That is a good idea, we can just link to the [roadmap](https://github.com/instantOS/instantOS/projects/1)

**Comment by con-f-use** [comment]
> I have a non-standard keyboard layout, how do I get hotkeys to work?

You don't :grinning:

**Comment by con-f-use** [comment]
@paperbenni @Pebor @hen6003 @uvera can you proofread my new answers and correct anything that might be wrong or unclear? We can merge this PR then.

**Comment by Pebor** [comment]
In language support, "My keyboard layout doesn't work" maybe a reminder that you can change your keybinds in config.def.h + recompile, should be able to get any layout workíng, and that remap-able keybinds are a plan for the future

**Comment by con-f-use** [comment]
@Pebor by all means, correct it!

**Comment by Pebor** [comment]
Sorry for my low level in this tech game but, how can I contribute into a PR?

**Comment by con-f-use** [comment]
image

picture above is probably the simplest way, but not sure if it will work for you because permissions. You can always do a commit to https://github.com/hen6003/instantos.github.io possible via a PR.

**Comment by Pebor** [comment]
Yeah, I didn't have permission, PR'ed on hen6003 fork

**Pull request merged**
